# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build ios app"
  lane :build_ios do 
    # Unlock an existing keychain and add it to the keychain search list
    unlock_keychain
    # match(
    #   type: "appstore",
    # )
    gym(
      workspace: "./Runner.xcworkspace",
      scheme: "Runner",
      output_directory: '../build/ios/ipa',
      output_name: 'ihsanmadani',
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "my.gov.onegovappstore.ihsanmadani" => "Ihsan MADANI",
        },
      },
    )
  end
  desc "Push to production"
  lane :deploy_ios_production do 
    upload_to_app_store(
      ipa: '../build/ios/ipa/ihsanmadani.ipa',
      skip_screenshots: true,
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
      },
      force: true,
    )
  end
end