# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new internal"
  lane :deploy_internal do
    upload_to_play_store(
      track: 'internal',
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      sync_image_upload: true,
    )
  end
  desc "Promote internal to alpha"
  lane :deploy_alpha do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'alpha',
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      sync_image_upload: true,
    )
  end
  desc "Promote internal to production"
  lane :deploy_production do
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      sync_image_upload: true,
    )
  end
end
